"use server";

import { revalidatePath } from "next/cache";
import { auth } from "@/auth";
import { canAccessDepartment, findDepartment } from "@/lib/access";
import { buildIndexMarkdown, listSops, parseFrontmatter } from "@/lib/sops";
import { listSoftwareCanons } from "@/lib/software";
import { allDevelopers, effectiveDeveloper, notifyEmails } from "@/lib/notify";
import { getSourceControl, sopPath } from "@/lib/source-control";

export type CommitSopResult =
  | { ok: true; sha: string; path: string }
  | { ok: false; error: string };

const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export async function commitSop(
  departmentSlug: string,
  topicSlug: string,
  content: string
): Promise<CommitSopResult> {
  const session = await auth();
  if (!session?.user) return { ok: false, error: "Not signed in" };

  const department = await findDepartment(departmentSlug);
  if (!department) return { ok: false, error: "Unknown department" };
  if (!(await canAccessDepartment(session, department.id))) {
    return { ok: false, error: "You don't have access to this department" };
  }
  if (!SLUG_RE.test(topicSlug)) {
    return { ok: false, error: "Topic slug must be kebab-case (a-z, 0-9, dashes)" };
  }
  if (!content.trim()) return { ok: false, error: "The draft is empty" };

  const path = `${sopPath()}/${department.slug}/${topicSlug}.md`;
  const provider = getSourceControl();
  try {
    // Snapshot the folder BEFORE committing (read-after-write on the GitHub
    // contents API can lag), then overlay the new SOP to build the index.
    const existing = await listSops(department.slug).catch(() => []);

    const sha = await provider.commitFile(
      path,
      content,
      `SOP: ${department.name} / ${topicSlug} (via Forward Deploy, by ${
        session.user.name ?? session.user.email
      })`
    );

    // Regenerate the department's INDEX.md - the Canonify-style breadth map.
    // Best-effort: an index failure never fails the SOP commit itself.
    try {
      const fm = parseFrontmatter(content);
      const overlaid = existing.filter((s) => s.slug !== topicSlug);
      overlaid.push({
        path,
        slug: topicSlug,
        topic: fm.topic || topicSlug,
        owner: fm.owner ?? "",
        updated: fm.updated ?? "",
        tools: (fm.tools ?? "")
          .replace(/^\[/, "")
          .replace(/\]$/, "")
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean),
        content,
      });
      await provider.commitFile(
        `${sopPath()}/${department.slug}/INDEX.md`,
        buildIndexMarkdown(department.name, overlaid),
        `SOP index: ${department.name} (regenerated by Forward Deploy)`
      );
    } catch {
      // index regeneration is best-effort; the next commit will catch it up
    }

    // Nudge the department's developer about newly-mentioned software that
    // has no canon yet - chosen over auto-research so a human still reviews
    // every canon before it's committed. Best-effort.
    try {
      const fm = parseFrontmatter(content);
      const tools = (fm.tools ?? "")
        .replace(/^\[/, "")
        .replace(/\]$/, "")
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean);
      if (tools.length) {
        const canons = await listSoftwareCanons().catch(() => []);
        const known = new Set(
          canons.flatMap((c) =>
            [c.software, c.slug, ...(c.aliases ?? [])].map((n) =>
              n.toLowerCase().replace(/[^a-z0-9]+/g, "")
            )
          )
        );
        const undocumented = tools.filter(
          (t) => !known.has(t.toLowerCase().replace(/[^a-z0-9]+/g, ""))
        );
        if (undocumented.length) {
          const dev = await effectiveDeveloper(department.id);
          const targets = dev
            ? [dev.email]
            : (await allDevelopers()).map((d) => d.email);
          const slugs = undocumented
            .map((t) => t.toLowerCase().replace(/[^a-z0-9]+/g, "-"))
            .join(", ");
          await notifyEmails(
            targets.filter((e) => e !== session.user.email),
            `[Forward Deploy] Undocumented software in a ${department.name} SOP`,
            `The SOP "${topicSlug}" in ${department.name} mentions software with no canon yet: ${undocumented.join(", ")}.\nRun /forward-deploy:capture-software ${slugs} to research it.`
          );
        }
      }
    } catch {
      // nudges never fail the commit
    }

    revalidatePath("/sops");
    revalidatePath(`/sops/${department.slug}`);
    return { ok: true, sha, path };
  } catch (e) {
    return { ok: false, error: `Commit failed: ${(e as Error).message}` };
  }
}
